### ISSUE TITLE
visibility on black-on-white terminals

### ISSUE THREAD

**Issue by top-on** [top-on/optimal-congress#2]
creating this dedicated issue for the comment by @dreirund in #1 :

> However I see that you have hard-coded a colour scheme that is not well
> visible on black-on-white terminals. Can you include some way to make
> it compatible with light terminal colour schemes?, e.g.
> 
> * by allowing to specify the colour scheme,
> * by allowing a non-coloured version,
> * by autodetecting (I don't know if it is possible) the terminal
>   colours?

**Comment by top-on** [comment]
@dreirund, here are two examples of what it looks like on my machine, if i switch to a black-on-white terminal:

![image](https://github.com/top-on/optimal-congress/assets/6625253/80ed2ac9-3191-4a1c-b75f-b38458f610cc)
![image](https://github.com/top-on/optimal-congress/assets/6625253/c0c7cd9d-fe62-4f9c-a94d-1cfb6eeca043)

hope this matches what you see?
if yes, could you please explain what you are missing, in terms of readability?

**Comment by dreirund** [comment]
> *here are two examples of what it looks like on my machine, if i switch to a black-on-white terminal:*

Here a screenshot of `optimal-congress --help`:  

---

![optimal-congress-help-output-on-blackonwhite-terminal](https://github.com/top-on/optimal-congress/assets/1590519/2406543d-0fa2-45ff-a951-56c7254e17ed)

---

The coloured parts are not easily readable (for me).

**Comment by top-on** [comment]
@dreirund, thanks for the visual example.
unfortunately, on my machine i get the same output on black and white, also for `--help`.

this [stackoverflow answer](https://stackoverflow.com/a/73217600) suggests that installting `typer` without any extras (compared to as in `pip install typer[all]`) should result in a non-color output.

interestingly, this project's `pyproject.toml` does not define any extras for `typer`.
but if i change the `typer` dependency definition in `pyproject.toml` to "`typer = { version = "^0.9.0", extras = ["all"] }`, i can resproduce the colorful output you see.

but i agree with you: the colors are not needed, and may only cause trouble in terms of readability.

do you see an option to change your build settings, to avoid installing `typer`'s extras (esp. `rich` and `colorama`)?

**Comment by dreirund** [comment]
Ahoj,

I use [my distrubution's packaging](https://aur.archlinux.org/packages/optimal-congress-git) and do not any manual python stuff.

Installed on my system is [`python-typer` version 0.9.0](https://archlinux.org/packages/extra/any/python-typer/).

I don't know anything how python specific packaging stuff works, I hade "third party" packaging that interferes with system packaging.

But I see in your `pyproject.toml` that there indeed is `typer` listed:  
```
[...]
[tool.poetry.dependencies]
[...]
typer = "^0.9.0"
[...]
```

`python-rich` and `python-colorama` I cannot uninstall from my system since they are required by other packages.

Anyway, if some random presence of packages changes colouring in an uncontrolled way: Wouldn't then be the clean way of doing it to program the software that it either always does colouring or never does, but not dependend on the presence of random unrelated packages?

Regards!

**Comment by dreirund** [comment]
.. setting the environment variable `NO_COLOR` (i.e. having at present, regardless of the value) disables colouring for me.

**Comment by top-on** [comment]
@dreirund, i ike the idea of adding color management, and then setting it to no colors.
and thanks a lot for pointing to the right env variable.

i will cook up a color fix soon, that will probably add rich as a dependency and will set the environmental variable programmatically.

**Comment by top-on** [comment]
@dreirund , the fix is now [released](https://github.com/top-on/optimal-congress/releases/tag/0.7.1). could you be so kind and check if your Arch build is now without colors, even if you are not setting `NO_COLOR` yourself?

**Comment by dreirund** [comment]
> could you be so kind and check if your Arch build is now without
> colors, even if you are not setting `NO_COLOR` yourself?

Checked & works.

**Comment by top-on** [comment]
great to hear!
